name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# explanation:
# - Run the workflow on every push to the main branch.
# - Run the workflow whenever a pull request is created to the main branch.

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
          
      - name: Run unit tests with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app

# explanation:
# A job called build is added to the workflow.
# This job will run on the latest ubuntu-latest runner.
# Tell Github Actions to use python:3.9-slim as the image.
# It is important to consistently use the same version of dependencies and
#   OS for all phases of development including the CI pipeline.